kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcp-filestore-csi-snapshotter-binding
subjects:
  - kind: ServiceAccount
    name: gcp-filestore-csi-driver-controller-sa
    namespace: ${NAMESPACE}
roleRef:
  kind: ClusterRole
  name: gcp-filestore-external-snapshotter-role
  apiGroup: rbac.authorization.k8s.io
