apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: gcp-filestore-csi-driver-operator.v4.17.0
  namespace: placeholder
  annotations:
    categories: Storage
    "operatorframework.io/suggested-namespace": openshift-cluster-csi-drivers
    capabilities: Full Lifecycle
    containerImage: quay.io/openshift/origin-gcp-filestore-csi-driver-operator:latest
    support: Red Hat
    operators.openshift.io/infrastructure-features: '["csi"]'
    repository: https://github.com/openshift/gcp-filestore-csi-driver-operator
    createdAt: "2021-07-14T00:00:00Z"
    description: Install and configure GCP Filestore CSI driver.
    olm.skipRange: ">=4.11.0-0 <4.17.0"
    features.operators.openshift.io/disconnected: "true"
    features.operators.openshift.io/fips-compliant: "true"
    features.operators.openshift.io/proxy-aware: "true"
    features.operators.openshift.io/tls-profiles: "true"
    features.operators.openshift.io/token-auth-aws: "false"
    features.operators.openshift.io/token-auth-azure: "false"
    features.operators.openshift.io/token-auth-gcp: "false"
    features.operators.openshift.io/csi: "true"
  labels:
    operator-metering: "true"
    "operatorframework.io/arch.amd64": supported
    "operatorframework.io/arch.arm64": supported
spec:
  displayName: GCP Filestore CSI Driver Operator
  description: >
    Operator that installs and configures the CSI driver for GCP Filestore.
  icon:
    - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
      mediatype: image/svg+xml
  keywords:
    - storage
    - filestore
  links:
    - name: Documentation
      url: https://github.com/openshift/gcp-filestore-csi-driver-operator
    - name: Source Repository
      url: https://github.com/openshift/gcp-filestore-csi-driver-operator
  version: 4.17.0
  maturity: stable
  maintainers:
    - email: aos-storage-staff@redhat.com
      name: Red Hat
  minKubeVersion: 1.21.0
  provider:
    name: Red Hat
  labels:
    alm-owner-metering: gcp-filestore-csi-driver-operator
    alm-status-descriptors: gcp-filestore-csi-driver-operator.v4.17.0
  selector:
    matchLabels:
      alm-owner-metering: gcp-filestore-csi-driver-operator
  installModes:
  - type: OwnNamespace
    supported: false
  - type: SingleNamespace
    supported: false
  - type: MultiNamespace
    supported: false
  - type: AllNamespaces
    supported: true
  install:
    strategy: deployment
    spec:
      permissions:
        - rules:
          - apiGroups:
            - ''
            resources:
            - pods
            - services
            - endpoints
            - events
            - configmaps
            - secrets
            verbs:
            - '*'
          - apiGroups:
            - apps
            resources:
            - deployments
            - daemonsets
            - replicasets
            verbs:
            - '*'
          - apiGroups:
            - monitoring.coreos.com
            resources:
            - servicemonitors
            verbs:
            - '*'
          serviceAccountName: gcp-filestore-csi-driver-operator
      clusterPermissions:
        - rules:
          - apiGroups:
            - security.openshift.io
            resourceNames:
            - privileged
            resources:
            - securitycontextconstraints
            verbs:
            - use
          - apiGroups:
            - operator.openshift.io
            resources:
            - clustercsidrivers
            verbs:
            - get
            - list
            - watch
            # The Config Observer controller updates the CR's spec
            - update
            - patch
          - apiGroups:
            - operator.openshift.io
            resources:
            - clustercsidrivers/status
            verbs:
            - get
            - list
            - watch
            - update
            - patch
          - apiGroups:
            - ''
            resourceNames:
            - extension-apiserver-authentication
            - gcp-filestore-csi-driver-operator-lock
            resources:
            - configmaps
            verbs:
            - '*'
          - apiGroups:
            - rbac.authorization.k8s.io
            resources:
            - clusterroles
            - clusterrolebindings
            - roles
            - rolebindings
            verbs:
            - watch
            - list
            - get
            - create
            - delete
            - patch
            - update
          - apiGroups:
            - ''
            resources:
            - serviceaccounts
            verbs:
            - get
            - list
            - watch
            - create
            - update
            - patch
            - delete
          - apiGroups:
            - coordination.k8s.io
            resources:
            - leases
            verbs:
            - '*'
          - apiGroups:
            - ''
            resources:
            - secrets
            verbs:
            - get
            - list
            - watch
          - apiGroups:
            - ''
            resources:
            - persistentvolumes
            verbs:
            - create
            - delete
            - list
            - get
            - watch
            - update
            - patch
          - apiGroups:
            - ''
            resources:
            - persistentvolumeclaims
            verbs:
            - get
            - list
            - watch
            - update
          - apiGroups:
            - ''
            resources:
            - persistentvolumeclaims/status
            verbs:
            - update
            - patch
          - apiGroups:
            - storage.k8s.io
            resources:
            - volumeattachments
            verbs:
            - get
            - list
            - watch
            - update
            - delete
            - create
            - patch
          - apiGroups:
            - storage.k8s.io
            resources:
            - volumeattachments/status
            verbs:
            - patch
          - apiGroups:
            - storage.k8s.io
            resources:
            - storageclasses
            - csinodes
            verbs:
            - create
            - get
            - list
            - watch
            - update
            - delete
          - apiGroups:
            - snapshot.storage.k8s.io
            resources:
            - volumesnapshotclasses
            - volumesnapshots
            - volumesnapshotcontents
            verbs:
            - create
            - get
            - list
            - watch
            - update
            - delete
            - patch
          - apiGroups:
            - snapshot.storage.k8s.io
            resources:
            - volumesnapshotcontents/status
            verbs:
            - update
            - patch
          - apiGroups:
            - apiextensions.k8s.io
            resources:
            - customresourcedefinitions
            verbs:
            - create
            - list
            - watch
            - delete
          - apiGroups:
            - policy
            resources:
            - poddisruptionbudgets
            verbs:
            - create
            - list
            - get
            - watch
            - update
            - delete
          - apiGroups:
            - '*'
            resources:
            - events
            verbs:
            - get
            - patch
            - create
            - list
            - watch
            - update
            - delete
          - apiGroups:
            - storage.k8s.io
            resources:
            - csidrivers
            verbs:
            - create
            - get
            - list
            - watch
            - update
            - delete
          - apiGroups:
            - cloudcredential.openshift.io
            resources:
            - credentialsrequests
            verbs:
            - '*'
          - apiGroups:
            - operator.openshift.io
            resources:
            - cloudcredentials
            verbs:
            - get
            - list
            - watch
          - apiGroups:
            - config.openshift.io
            resources:
            - infrastructures
            - proxies
            - apiservers
            verbs:
            - get
            - list
            - watch
          - apiGroups:
            - authentication.k8s.io
            resources:
            - tokenreviews
            verbs:
            - create
          - apiGroups:
            - ""
            resources:
            - nodes
            verbs:
            - get
            - list
            - watch
          serviceAccountName: gcp-filestore-csi-driver-operator
      deployments:
        - name: gcp-filestore-csi-driver-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: gcp-filestore-csi-driver-operator
            template:
              metadata:
                annotations:
                  target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
                labels:
                  app: gcp-filestore-csi-driver-operator
              spec:
                serviceAccountName: gcp-filestore-csi-driver-operator
                containers:
                - name: gcp-filestore-csi-driver-operator
                  image: quay.io/openshift/origin-gcp-filestore-csi-driver-operator:latest
                  imagePullPolicy: IfNotPresent
                  args:
                    - "start"
                    - "-v=2"
                  env:
                    - name: POD_NAME
                      valueFrom:
                        fieldRef:
                          fieldPath: metadata.name
                    - name: DRIVER_IMAGE
                      value: quay.io/openshift/origin-gcp-filestore-csi-driver:latest
                    - name: PROVISIONER_IMAGE
                      value: quay.io/openshift/origin-csi-external-provisioner:latest
                    - name: RESIZER_IMAGE
                      value: quay.io/openshift/origin-csi-external-resizer:latest
                    - name: SNAPSHOTTER_IMAGE
                      value: quay.io/openshift/origin-csi-external-snapshotter:latest
                    - name: NODE_DRIVER_REGISTRAR_IMAGE
                      value: quay.io/openshift/origin-csi-node-driver-registrar:latest
                    - name: LIVENESS_PROBE_IMAGE
                      value: quay.io/openshift/origin-csi-livenessprobe:latest
                    - name: OPERATOR_NAME
                      value: gcp-filestore-csi-driver-operator
                    - name: KUBE_RBAC_PROXY_IMAGE
                      value: quay.io/openshift/origin-kube-rbac-proxy:latest
                  resources:
                    requests:
                      memory: 50Mi
                      cpu: 10m
                  terminationMessagePolicy: FallbackToLogsOnError
                priorityClassName: system-cluster-critical
                # Strongly prefer a master node, but don't require it.
                # We want the same Deployment to work on hypershift,
                # without any master nodes.
                affinity:
                  nodeAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 100
                      preference:
                        matchExpressions:
                        - key: node-role.kubernetes.io/master
                          operator: In
                          values:
                          - ""
                tolerations:
                  - key: CriticalAddonsOnly
                    operator: Exists
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                    effect: "NoSchedule"
